spring.application.name=spring_security
spring.security.user.name=admin
spring.security.user.password=test

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test


spring.app.jwtSecret=cXdldHVzYWdkaGpkc2pmdTN5N2lyNjg2NDNyeXJoZWdkc3Z3aGZoaTNyZXVodmVoZHNnZnJldWQ=
spring.app.jwtExpirationMs=86400000
spring.springSecurity.app.jwtCookie=springSecurity

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.gomad.spring_security=DEBUG