spring.application.name=complete_tutorial
server.servlet.context-path=/api

#Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/employees

# Postgresql Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO
logging.level.com.gomad.spring_security=INFO


spring.app.jwtSecret=cXdldHVzYWdkaGpkc2pmdTN5N2lyNjg2NDNyeXJoZWdkc3Z3aGZoaTNyZXVodmVoZHNnZnJldWQ=
spring.app.jwtExpirationMs=86400000
spring.springSecurity.app.jwtCookie=springSecurity