spring.application.name=postgresql_tut
server.servlet.context-path=/api/public

#Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/employees

# Postgresql Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.security=INFO
logging.level.com.gomad.spring_security=INFO